import React, { useState, useEffect } from 'react';
import { Line } from 'react-chartjs-2';
import { User, Award, Heart, TrendingUp, Download, Bell } from 'lucide-react';
import { analyticsAPI } from '../services/api';
import './ParentDashboard.css';

const ParentDashboard = ({ user }) => {
  const [loading, setLoading] = useState(true);
  const [analytics, setAnalytics] = useState(null);

  useEffect(() => {
    fetchDashboardData();
  }, [user]);

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      // Assuming parentOf contains the child's ID
      const childId = user.parentOf || user.id;
      const res = await analyticsAPI.getParentDashboard(childId);
      setAnalytics(res.data);
    } catch (error) {
      console.error('Error fetching dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
    if (!analytics) {
      alert('No data available to download');
      return;
    }

    // Create report content
    const reportContent = `
EduHealth Nexus - Student Progress Report
==========================================
Generated: ${new Date().toLocaleDateString()}

STUDENT INFORMATION
-------------------
Name: ${analytics.childInfo?.name || 'N/A'}
Class: ${analytics.childInfo?.class || 'N/A'}

ACADEMIC PERFORMANCE
--------------------
Average Score: ${analytics.performance?.avgScore || 0}%
Total Quizzes: ${analytics.performance?.totalQuizzes || 0}
Best Score: ${analytics.performance?.bestScore || 0}%

Recent Quiz Scores:
${analytics.performance?.recentAttempts?.slice(0, 5).map((attempt, i) => 
  `${i + 1}. ${attempt.quiz?.title || 'Quiz'}: ${attempt.percentage}%`
).join('\n') || 'No recent quizzes'}

HEALTH METRICS
--------------
Average Sleep: ${analytics.health?.avgSleep || 0} hours
Average Stress Level: ${analytics.health?.avgStress || 0}/10
Average Heart Rate: ${analytics.health?.avgHeartRate || 0} bpm

RECOMMENDATIONS
---------------
${analytics.health?.avgSleep < 7 ? '⚠ Sleep: Encourage more sleep (7-9 hours recommended)\n' : ''}
${analytics.health?.avgStress > 6 ? '⚠ Stress: High stress levels detected - consider relaxation activities\n' : ''}
${analytics.performance?.avgScore < 70 ? '⚠ Academic: Additional study support may be beneficial\n' : ''}
${analytics.performance?.avgScore >= 80 ? '✓ Academic: Excellent performance!\n' : ''}
${analytics.health?.avgSleep >= 7 && analytics.health?.avgSleep <= 9 ? '✓ Sleep: Good sleep habits\n' : ''}

==========================================
Report generated by EduHealth Nexus
For questions, contact: support@eduhealth.com
    `.trim();

    // Create blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Student_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="dashboard-loading">
        <div className="spinner"></div>
        <p>Loading dashboard...</p>
      </div>
    );
  }

  const performanceData = {
    labels: analytics?.performance?.recentAttempts?.slice(0, 7).reverse().map((_, i) => `Quiz ${i + 1}`) || [],
    datasets: [
      {
        label: 'Quiz Scores',
        data: analytics?.performance?.recentAttempts?.slice(0, 7).reverse().map(a => a.percentage) || [],
        borderColor: '#6C63FF',
        backgroundColor: 'rgba(108, 99, 255, 0.1)',
        fill: true,
        tension: 0.4
      }
    ]
  };

  const healthData = {
    labels: analytics?.health?.recentData?.reverse().map((_, i) => `Day ${i + 1}`) || [],
    datasets: [
      {
        label: 'Sleep Hours',
        data: analytics?.health?.recentData?.map(h => h.sleepHours) || [],
        borderColor: '#00C9A7',
        backgroundColor: 'rgba(0, 201, 167, 0.1)',
        fill: true,
        tension: 0.4
      }
    ]
  };

  return (
    <div className="parent-dashboard">
      <div className="dashboard-header">
        <div>
          <h1>Parent Dashboard</h1>
          <p>Monitor your child's progress and well-being</p>
        </div>
        <button className="btn-download" onClick={downloadReport}>
          <Download size={18} />
          Download Report
        </button>
      </div>

      {/* Child Info */}
      <div className="child-info-card">
        <div className="child-avatar">
          <User size={40} />
        </div>
        <div className="child-details">
          <h2>{analytics?.child?.name}</h2>
          <p>Student ID: {analytics?.child?.studentId}</p>
          <p>Class: {analytics?.child?.class}</p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #6C63FF, #00C9A7)' }}>
            <Award />
          </div>
          <div className="stat-content">
            <span className="stat-label">Average Score</span>
            <span className="stat-value">{analytics?.performance?.avgScore || 0}%</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #00C9A7, #FFD166)' }}>
            <TrendingUp />
          </div>
          <div className="stat-content">
            <span className="stat-label">Quizzes Completed</span>
            <span className="stat-value">{analytics?.performance?.totalQuizzes || 0}</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #FFD166, #FF6B6B)' }}>
            <Heart />
          </div>
          <div className="stat-content">
            <span className="stat-label">Avg Sleep</span>
            <span className="stat-value">{analytics?.health?.avgSleep || 0}h</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #FF6B6B, #6C63FF)' }}>
            <Bell />
          </div>
          <div className="stat-content">
            <span className="stat-label">Alerts</span>
            <span className="stat-value">{analytics?.notifications?.length || 0}</span>
          </div>
        </div>
      </div>

      {/* Notifications */}
      {analytics?.notifications && analytics.notifications.length > 0 && (
        <div className="notifications-section">
          <h2 className="section-title">
            <Bell />
            Important Notifications
          </h2>
          <div className="notifications-list">
            {analytics.notifications.map((notif, index) => (
              <div key={index} className={`notification-card ${notif.type}`}>
                <div className="notif-icon">
                  <Bell size={20} />
                </div>
                <div className="notif-content">
                  <h4>{notif.message}</h4>
                  <p>Value: {notif.value}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Charts */}
      <div className="charts-section">
        <div className="chart-card">
          <h3>
            <TrendingUp size={20} />
            Academic Performance
          </h3>
          <Line 
            data={performanceData}
            options={{
              responsive: true,
              maintainAspectRatio: false,
              plugins: { legend: { display: false } },
              scales: { y: { beginAtZero: true, max: 100 } }
            }}
          />
        </div>

        <div className="chart-card">
          <h3>
            <Heart size={20} />
            Sleep Pattern
          </h3>
          <Line 
            data={healthData}
            options={{
              responsive: true,
              maintainAspectRatio: false,
              plugins: { legend: { display: false } }
            }}
          />
        </div>
      </div>

      {/* Recent Activity */}
      <div className="activity-section">
        <h2 className="section-title">Recent Quiz Attempts</h2>
        <div className="activity-list">
          {analytics?.performance?.recentAttempts?.slice(0, 5).map((attempt, index) => (
            <div key={index} className="activity-item">
              <div className="activity-info">
                <h4>{attempt.quiz?.title}</h4>
                <p>{attempt.quiz?.subject}</p>
              </div>
              <div className="activity-score">
                <span className={attempt.percentage >= 60 ? 'score-good' : 'score-poor'}>
                  {attempt.percentage}%
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ParentDashboard;
