import React, { useState, useEffect } from 'react';
import { Bar, Doughnut } from 'react-chartjs-2';
import {
  Users, Award, AlertTriangle, TrendingUp, Plus, Edit, Trash2, Eye, Calendar, Download
} from 'lucide-react';
import { quizAPI, analyticsAPI } from '../services/api';
import AttendanceSection from '../components/AttendanceSection';
import './TeacherDashboard.css';

const TeacherDashboard = ({ user }) => {
  const [loading, setLoading] = useState(true);
  const [analytics, setAnalytics] = useState(null);
  const [quizzes, setQuizzes] = useState([]);
  const [students, setStudents] = useState([]);
  const [showCreateQuiz, setShowCreateQuiz] = useState(false);
  const [showStudentsList, setShowStudentsList] = useState(false);
  const [showAttendance, setShowAttendance] = useState(false);
  const [newQuiz, setNewQuiz] = useState({
    title: '',
    description: '',
    subject: '',
    duration: 30,
    questions: []
  });

  useEffect(() => {
    fetchDashboardData();
  }, []);

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      const [analyticsRes, quizzesRes, studentsRes] = await Promise.all([
        analyticsAPI.getTeacherDashboard(),
        quizAPI.getAll(),
        analyticsAPI.getAllStudents()
      ]);
      
      setAnalytics(analyticsRes.data);
      setQuizzes(quizzesRes.data.quizzes);
      setStudents(studentsRes.data.students);
    } catch (error) {
      console.error('Error fetching dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateQuiz = async (e) => {
    e.preventDefault();
    try {
      await quizAPI.create(newQuiz);
      setShowCreateQuiz(false);
      setNewQuiz({
        title: '',
        description: '',
        subject: '',
        duration: 30,
        questions: []
      });
      fetchDashboardData();
    } catch (error) {
      console.error('Error creating quiz:', error);
    }
  };

  const handleDeleteQuiz = async (quizId) => {
    if (window.confirm('Are you sure you want to delete this quiz?')) {
      try {
        await quizAPI.delete(quizId);
        fetchDashboardData();
      } catch (error) {
        console.error('Error deleting quiz:', error);
      }
    }
  };

  const downloadReport = () => {
    if (!analytics) {
      alert('No data available to download');
      return;
    }

    const reportContent = `
EduHealth Nexus - Teacher Dashboard Report
==========================================
Generated: ${new Date().toLocaleDateString()}

TEACHER INFORMATION
-------------------
Name: ${user.name}
Email: ${user.email}
Role: Teacher

CLASS OVERVIEW
--------------
Total Students: ${analytics?.totalStudents || 0}
Class Average Score: ${analytics?.classAverage || 0}%
Total Quizzes Created: ${quizzes?.length || 0}

STUDENT PERFORMANCE
-------------------
Top Performers:
${analytics?.topPerformers?.slice(0, 5).map((attempt, i) => 
  `${i + 1}. ${attempt.student?.name || 'Student'}: ${attempt.percentage}% (${attempt.quiz?.title})`
).join('\n') || 'No data available'}

Students Needing Attention:
${analytics?.lowPerformers?.slice(0, 5).map((attempt, i) => 
  `${i + 1}. ${attempt.student?.name || 'Student'}: ${attempt.percentage}% (${attempt.quiz?.title})`
).join('\n') || 'No data available'}

HEALTH CONCERNS
---------------
Students with Health Issues: ${analytics?.healthConcerns?.length || 0}
${analytics?.healthConcerns?.slice(0, 5).map((concern, i) => 
  `${i + 1}. ${concern.student?.name || 'Student'}: Sleep ${concern.sleepHours}h, Stress ${concern.stressLevel}/10`
).join('\n') || 'No health concerns'}

QUIZ STATISTICS
---------------
Active Quizzes: ${quizzes?.length || 0}
${quizzes?.slice(0, 5).map((quiz, i) => 
  `${i + 1}. ${quiz.title} (${quiz.subject}) - ${quiz.duration} mins`
).join('\n') || 'No quizzes created'}

RECOMMENDATIONS
---------------
${analytics?.lowPerformers?.length > 5 ? '⚠ Academic: Several students need additional support\n' : ''}
${analytics?.healthConcerns?.length > 3 ? '⚠ Health: Multiple students showing health concerns\n' : ''}
${analytics?.classAverage >= 80 ? '✓ Performance: Excellent class performance!\n' : ''}
${analytics?.classAverage < 70 ? '⚠ Performance: Consider reviewing teaching methods or providing extra help\n' : ''}

==========================================
Report generated by EduHealth Nexus
For support, contact: support@eduhealth.com
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Teacher_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const addQuestion = () => {
    setNewQuiz({
      ...newQuiz,
      questions: [
        ...newQuiz.questions,
        {
          question: '',
          options: ['', '', '', ''],
          correctAnswer: 0,
          points: 1
        }
      ]
    });
  };

  if (loading) {
    return (
      <div className="dashboard-loading">
        <div className="spinner"></div>
        <p>Loading dashboard...</p>
      </div>
    );
  }

  const performanceData = {
    labels: ['Excellent (80-100%)', 'Good (60-79%)', 'Average (40-59%)', 'Poor (<40%)'],
    datasets: [
      {
        label: 'Student Distribution',
        data: [30, 40, 20, 10],
        backgroundColor: ['#00C9A7', '#6C63FF', '#FFD166', '#FF6B6B']
      }
    ]
  };

  return (
    <div className="teacher-dashboard">
      <div className="dashboard-header">
        <div>
          <h1>Teacher Dashboard</h1>
          <p>Manage quizzes, attendance, and monitor student performance</p>
        </div>
        <div className="header-buttons">
          <button onClick={downloadReport} className="btn-download">
            <Download size={18} />
            Download Report
          </button>
          <button onClick={() => setShowAttendance(!showAttendance)} className="btn-attendance">
            <Calendar size={18} />
            {showAttendance ? 'Hide' : 'Show'} Attendance
          </button>
          <button onClick={() => setShowCreateQuiz(true)} className="btn-create">
            <Plus size={18} />
            Create Quiz
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #6C63FF, #00C9A7)' }}>
            <Users />
          </div>
          <div className="stat-content">
            <span className="stat-label">Total Students</span>
            <span className="stat-value">{analytics?.totalStudents || 0}</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #00C9A7, #FFD166)' }}>
            <Award />
          </div>
          <div className="stat-content">
            <span className="stat-label">Class Average</span>
            <span className="stat-value">{analytics?.classAverage || 0}%</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #FFD166, #FF6B6B)' }}>
            <TrendingUp />
          </div>
          <div className="stat-content">
            <span className="stat-label">Total Attempts</span>
            <span className="stat-value">{analytics?.totalAttempts || 0}</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'linear-gradient(135deg, #FF6B6B, #6C63FF)' }}>
            <AlertTriangle />
          </div>
          <div className="stat-content">
            <span className="stat-label">Health Alerts</span>
            <span className="stat-value">{analytics?.healthConcerns?.length || 0}</span>
          </div>
        </div>
      </div>

      {/* Attendance Section */}
      {showAttendance && <AttendanceSection />}

      {/* Alerts Section */}
      {analytics?.lowPerformers?.length > 0 && (
        <div className="alerts-section">
          <h2 className="section-title">
            <AlertTriangle />
            Students Needing Attention
          </h2>
          <div className="alerts-grid">
            {analytics.lowPerformers.slice(0, 5).map((attempt, index) => (
              <div key={index} className="alert-card">
                <div className="alert-header">
                  <span className="student-name">{attempt.student?.name}</span>
                  <span className="alert-score">{attempt.percentage}%</span>
                </div>
                <p className="alert-quiz">{attempt.quiz?.title}</p>
                <span className="alert-badge">Low Performance</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Health Concerns */}
      {analytics?.healthConcerns?.length > 0 && (
        <div className="health-concerns-section">
          <h2 className="section-title">Health Concerns</h2>
          <div className="concerns-grid">
            {analytics.healthConcerns.map((concern, index) => (
              <div key={index} className="concern-card">
                <h4>{concern.student.name}</h4>
                <div className="concern-metrics">
                  <div className="metric">
                    <span>Sleep:</span>
                    <strong>{concern.healthData.sleepHours}h</strong>
                  </div>
                  <div className="metric">
                    <span>Stress:</span>
                    <strong>{concern.healthData.stressLevel}/10</strong>
                  </div>
                  <div className="metric">
                    <span>Heart Rate:</span>
                    <strong>{concern.healthData.heartRate} bpm</strong>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Performance Chart */}
      <div className="chart-section">
        <h2 className="section-title">Class Performance Distribution</h2>
        <div className="chart-container">
          <Doughnut 
            data={performanceData}
            options={{
              responsive: true,
              maintainAspectRatio: false,
              plugins: {
                legend: { position: 'bottom' }
              }
            }}
          />
        </div>
      </div>

      {/* All Registered Students */}
      <div className="students-section">
        <div className="section-header">
          <h2 className="section-title">
            <Users />
            All Registered Students ({students.length})
          </h2>
          <button 
            onClick={() => setShowStudentsList(!showStudentsList)} 
            className="btn-toggle"
          >
            {showStudentsList ? 'Hide' : 'Show'} Students
          </button>
        </div>

        {showStudentsList && (
          <div className="students-table-container">
            <table className="students-table">
              <thead>
                <tr>
                  <th>Student ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Class</th>
                  <th>Quizzes Taken</th>
                  <th>Avg Score</th>
                  <th>Avg Sleep</th>
                  <th>Avg Stress</th>
                  <th>Latest Health</th>
                  <th>Registered</th>
                </tr>
              </thead>
              <tbody>
                {students.map((student) => (
                  <tr key={student._id}>
                    <td>{student.studentId || 'N/A'}</td>
                    <td className="student-name-cell">{student.name}</td>
                    <td>{student.email}</td>
                    <td>{student.class || 'Not Set'}</td>
                    <td>{student.stats.totalQuizzes}</td>
                    <td>
                      <span className={`score-badge ${
                        student.stats.avgScore >= 80 ? 'excellent' : 
                        student.stats.avgScore >= 60 ? 'good' : 
                        student.stats.avgScore >= 40 ? 'average' : 'poor'
                      }`}>
                        {student.stats.avgScore}%
                      </span>
                    </td>
                    <td>
                      <span className={`health-badge ${
                        student.stats.avgSleep >= 7 ? 'good' : 
                        student.stats.avgSleep >= 5 ? 'warning' : 'danger'
                      }`}>
                        {student.stats.avgSleep}h
                      </span>
                    </td>
                    <td>
                      <span className={`health-badge ${
                        student.stats.avgStress <= 4 ? 'good' : 
                        student.stats.avgStress <= 7 ? 'warning' : 'danger'
                      }`}>
                        {student.stats.avgStress}/10
                      </span>
                    </td>
                    <td>
                      {student.stats.latestHealth ? (
                        <div className="latest-health">
                          <span>💓 {student.stats.latestHealth.heartRate}</span>
                          <span>😊 {student.stats.latestHealth.mood}</span>
                        </div>
                      ) : (
                        <span className="no-data">No data</span>
                      )}
                    </td>
                    <td>{new Date(student.createdAt).toLocaleDateString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {students.length === 0 && (
              <div className="no-students">
                <Users size={48} />
                <p>No students registered yet</p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Quizzes List */}
      <div className="quizzes-section">
        <h2 className="section-title">My Quizzes</h2>
        <div className="quizzes-list">
          {quizzes.map((quiz) => (
            <div key={quiz._id} className="quiz-item">
              <div className="quiz-info">
                <h3>{quiz.title}</h3>
                <p>{quiz.description}</p>
                <div className="quiz-meta">
                  <span>{quiz.subject}</span>
                  <span>{quiz.questions.length} Questions</span>
                  <span>{quiz.duration} min</span>
                </div>
              </div>
              <div className="quiz-actions">
                <button className="btn-icon" title="View Attempts">
                  <Eye size={18} />
                </button>
                <button className="btn-icon" title="Edit">
                  <Edit size={18} />
                </button>
                <button 
                  className="btn-icon danger" 
                  onClick={() => handleDeleteQuiz(quiz._id)}
                  title="Delete"
                >
                  <Trash2 size={18} />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Create Quiz Modal */}
      {showCreateQuiz && (
        <div className="modal-overlay" onClick={() => setShowCreateQuiz(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h2>Create New Quiz</h2>
            <form onSubmit={handleCreateQuiz}>
              <div className="form-group">
                <label>Quiz Title</label>
                <input
                  type="text"
                  value={newQuiz.title}
                  onChange={(e) => setNewQuiz({ ...newQuiz, title: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <label>Description</label>
                <textarea
                  value={newQuiz.description}
                  onChange={(e) => setNewQuiz({ ...newQuiz, description: e.target.value })}
                  rows="3"
                />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Subject</label>
                  <input
                    type="text"
                    value={newQuiz.subject}
                    onChange={(e) => setNewQuiz({ ...newQuiz, subject: e.target.value })}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Duration (minutes)</label>
                  <input
                    type="number"
                    value={newQuiz.duration}
                    onChange={(e) => setNewQuiz({ ...newQuiz, duration: parseInt(e.target.value) })}
                    required
                  />
                </div>
              </div>

              <div className="questions-section">
                <div className="questions-header">
                  <h3>Questions</h3>
                  <button type="button" onClick={addQuestion} className="btn-add-question">
                    <Plus size={16} />
                    Add Question
                  </button>
                </div>
                {newQuiz.questions.map((q, qIndex) => (
                  <div key={qIndex} className="question-item">
                    <input
                      type="text"
                      placeholder="Question"
                      value={q.question}
                      onChange={(e) => {
                        const questions = [...newQuiz.questions];
                        questions[qIndex].question = e.target.value;
                        setNewQuiz({ ...newQuiz, questions });
                      }}
                      required
                    />
                    {q.options.map((opt, oIndex) => (
                      <div key={oIndex} className="option-input">
                        <input
                          type="radio"
                          name={`correct-${qIndex}`}
                          checked={q.correctAnswer === oIndex}
                          onChange={() => {
                            const questions = [...newQuiz.questions];
                            questions[qIndex].correctAnswer = oIndex;
                            setNewQuiz({ ...newQuiz, questions });
                          }}
                        />
                        <input
                          type="text"
                          placeholder={`Option ${oIndex + 1}`}
                          value={opt}
                          onChange={(e) => {
                            const questions = [...newQuiz.questions];
                            questions[qIndex].options[oIndex] = e.target.value;
                            setNewQuiz({ ...newQuiz, questions });
                          }}
                          required
                        />
                      </div>
                    ))}
                  </div>
                ))}
              </div>

              <div className="modal-actions">
                <button type="button" onClick={() => setShowCreateQuiz(false)} className="btn-cancel">
                  Cancel
                </button>
                <button type="submit" className="btn-submit">
                  Create Quiz
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default TeacherDashboard;
